apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cassandra
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv-cassandra
  persistentVolumeReclaimPolicy: Recycle
