apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cassandra
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-cassandra
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
